name:                termination-checker
version:             0.1.0.0
github:              "thealmarty/termination-checker"
license:             GPL3
author:              "Marty Stumpf"
maintainer:          "thealmartyblog@gmail.com"
copyright:           "2020 Marty Stumpf; 2020 Cryptium Labs"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/termination-checker#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- Cabal
- containers

default-extensions:
  - DeriveGeneric
  - UnicodeSyntax
  - OverloadedStrings
  - ScopedTypeVariables

library:
  source-dirs: src

executables:
  termination-checker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    dependencies:
    - termination-checker

tests:
  termination-checker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - termination-checker
