name:                totality-checker
version:             0.1.0.0
github:              "thealmarty/totality-checker"
license:             GPL-3
author:              "Marty Stumpf"
maintainer:          "thealmartyblog@gmail.com"
copyright:           "2020 Marty Stumpf; 2020 Metastate"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/totality-checker#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- Cabal
- containers
- HUnit
- HUnit-Plus
- semirings
- matrix

default-extensions:
  - DeriveGeneric
  - UnicodeSyntax
  - OverloadedStrings
  - ScopedTypeVariables

library:
  source-dirs: src

executables:
  totality-checker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    dependencies:
    - totality-checker

tests:
  totality-checker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - totality-checker
